### ISSUE TITLE
libsyntax-infix-smartmatch-perl: FTBFS: make: *** [debian/rules:6: binary] Error 25

### ISSUE THREAD

**Issue by gregoa** [Leont/syntax-infix-smartmatch#2]
We have the following bug reported to the Debian package of
Syntax-Infix-Smartmatch, c.f. https://bugs.debian.org/1077447

It doesn't seem to be a bug in the packaging, so you may want to take
a look. Thanks!

My first guess would be that this might be related to the changes
in XS-Parse-Keyword >= 0.43.

------8<-----------8<-----------8<-----------8<-----------8<-----

```
Source: libsyntax-infix-smartmatch-perl
Version: 0.005-2
Severity: serious
Justification: FTBFS
Tags: trixie sid ftbfs
User: lucas@debian.org
Usertags: ftbfs-20240728 ftbfs-trixie

Hi,

During a rebuild of all packages in sid, your package failed to build
on amd64.


Relevant part (hopefully):
>  debian/rules binary
> dh binary
>    dh_update_autotools_config
>    dh_autoreconf
>    dh_auto_configure
> 	/usr/bin/perl Build.PL --installdirs vendor --config "optimize=-g -O2 -Werror=implicit-function-declaration -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -Wdate-time -D_FORTIFY_SOURCE=2" --config "ld=x86_64-linux-gnu-gcc -g -O2 -Werror=implicit-function-declaration -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -Wl,-z,relro -Wl,-z,now"
> Creating new 'Build' script for 'Syntax-Infix-Smartmatch' version '0.005'
>    dh_auto_build
> 	/usr/bin/perl Build
> Undefined subroutine &XS::Parse::Infix::Builder_data::XSPARSEINFIX_H called at lib/Syntax/Infix/XSParseInfix.h.PL line 9.
> lib/Syntax/Infix/XSParseInfix.h.PL returned 6400
> dh_auto_build: error: /usr/bin/perl Build returned exit code 25
> make: *** [debian/rules:6: binary] Error 25


The full build log is available from:
http://qa-logs.debian.net/2024/07/28/libsyntax-infix-smartmatch-perl_0.005-2_unstable.log

All bugs filed during this archive rebuild are listed at:
https://bugs.debian.org/cgi-bin/pkgreport.cgi?tag=ftbfs-20240728;users=lucas@debian.org
or:
https://udd.debian.org/bugs/?release=na&merged=ign&fnewerval=7&flastmodval=7&fusertag=only&fusertagtag=ftbfs-20240728&fusertaguser=lucas@debian.org&allbugs=1&cseverity=1&ctags=1&caffected=1#results

A list of current common problems and possible solutions is available at
http://wiki.debian.org/qa.debian.org/FTBFS . You're welcome to contribute!

If you reassign this bug to another package, please mark it as 'affects'-ing
this package. See https://www.debian.org/Bugs/server-control#affects

If you fail to reproduce this, please provide a build log and diff it with mine
so that we can identify if something relevant changed in the meantime.


```
------8<-----------8<-----------8<-----------8<-----------8<-----

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by Leont** [comment]
Yeah I was slightly poking into private information of XS::Parse::Infix::Builder, and apparently that breaks now. Will fix it.

**Comment by gregoa** [comment]
On Tue, 30 Jul 2024 13:39:47 -0700, Leon Timmermans wrote:

> Yeah I was slightly poking into private information of XS::Parse::Infix::Builder, and apparently that breaks now. Will fix it.

Great news, thanks!


Cheers,
gregor 

-- 
 .''`.  https://info.comodo.priv.at -- Debian Developer https://www.debian.org
 : :' : OpenPGP fingerprint D1E1 316E 93A7 60A8 104D  85FA BB3A 6801 8649 AA06
 `. `'  Member VIBE!AT & SPI Inc. -- Supporter Free Software Foundation Europe
   `-

**Comment by Leont** [comment]
Should be fixed in 0.006. Do note that will bring in a few new configure-time dependencies (that other things may also start to depend on soonish).

**Comment by gregoa** [comment]
On Wed, 31 Jul 2024 14:25:29 -0700, Leon Timmermans wrote:

> Should be fixed in 0.006.

Thank you!

> Do note that will bring in a few new configure-time dependencies (that other things may also start to depend on soonish).

Yeah, looks like we have to package Dist::Build first (and maybe some
of its dependencies).


Cheers,
gregor 

-- 
 .''`.  https://info.comodo.priv.at -- Debian Developer https://www.debian.org
 : :' : OpenPGP fingerprint D1E1 316E 93A7 60A8 104D  85FA BB3A 6801 8649 AA06
 `. `'  Member VIBE!AT & SPI Inc. -- Supporter Free Software Foundation Europe
   `-

**Comment by Leont** [comment]
I think this can be closed now?

**Comment by gregoa** [comment]
Probably :)

For an upload to Debian, I need to wait for Dist::Build (and the other 2 new packages) to pass through the NEW queue (i.e. the one-time review of our ftp-masters for new packages), so I haven't checked so far.

But if you'd like to get this issue off your plate, please go ahead and close it, in case of any problems I can always come back.

Cheers,
gregor

**Comment by gregoa** [comment]
Dist::Build was accepted into Debian, and I've uploaded the fixed syntax-infix-smartmatch, hence closing this bug. Thanks again!
